env:
  global:
    secure: qFrFEjQ8N1w7qKsTi6hpwSl2VtjKJiIlvvwiAgvzZkiu/DlFZH+33cQcWVpIA0PofUQF94s+lTg4Y1dVMh4cbGOCA2mu1RaULPaGVGx1j4rRKaMg7GS1E3IthPfp0e6iYzHtFAFF+YK7JGkwk9kVNHWb3Wer7ES3Z3YOrFoE5hc=
language: rust
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential xorg-dev libudev-dev libts-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev libopenal-dev libogg-dev libvorbis-dev libaudiofile-dev libpng12-dev libfreetype6-dev libusb-dev libdbus-1-dev zlib1g-dev libdirectfb-dev
  - wget http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -xvzf SDL2-2.0.3.tar.gz
  - cd SDL2-2.0.3/ && ./configure && make && sudo make install && sudo ldconfig && cd ../
script:
  - cargo build --verbose
  - cargo test --verbose
  - cd chip8_vm/ && cargo test --verbose && cd ../
  - cargo doc --verbose
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=chip8_vm/index.html>' > target/doc/index.html &&
  sudo -H pip install --upgrade pip &&
  sudo -H pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
